live_config_reload = true

[font]
#size = 10.5
size = 11.5
offset.x = 0
offset.y = 0

[font.normal]
#family = "Comic Mono"
#family = "MesloLGS Nerd Font"
#family = "RobotoMono Nerd Font"
family = "MesloLGMDZ Nerd Font Mono"
#family = "ComicShannsMono Nerd Font"
#family = "JetBrainsMono Nerd Font"
style = "Bold"
#family = "Hack"

[window]
opacity = 0.95
title = "Terminal"
startup_mode = "Windowed"
dimensions = { columns = 88, lines = 33 }
padding = { x = 3, y = 3 }
dynamic_title = true

[cursor]
style = { blinking = "Always" }
blink_interval = 500

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x928374"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe3a84e"

[colors.normal]
black = "0x665c54"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xdfbf8e"
yellow = "0xe78a4e"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[env]
TERM = "alacritty"

[scrolling]
history = 100000

